apiVersion: tekton.dev/v1beta1
kind: Pipeline

metadata:
  name: demo-pipeline

spec:
  tasks:
    - name: clone-repo
      taskSpec:
        steps:
          - name: clone
            image: alpine/git
            script: |
              echo "Cloning repository"

---
apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerBinding

metadata:
  name: demo-binding

spec:
  params:
    - name: gitrevision
      value: $(body.head_commit.id)

---
apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerTemplate

metadata:
  name: demo-template

spec:
  params:
    - name: gitrevision

  resourcetemplates:
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun

      metadata:
        generateName: demo-pipeline-run-

      spec:
        pipelineRef:
          name: demo-pipeline

---
apiVersion: triggers.tekton.dev/v1beta1
kind: EventListener

metadata:
  name: demo-listener

spec:
  serviceAccountName: pipeline

  triggers:
    - bindings:
        - ref: demo-binding

      template:
        ref: demo-template
